pipeline {
    agent any

    environment {
        DOCKERHUB = credentials('d87db04c-92b2-4ade-ab17-ceba28868239')  // Jenkins credential ID: username + password
        APP_NAME = 'todo-list-fe'
        IMAGE_TAG = "${BUILD_NUMBER}"
    }

    stages {

        stage('Init') {
            steps {
                script {
                    env.BRANCH_NAME = sh(script: "git rev-parse --abbrev-ref HEAD", returnStdout: true).trim()
                    echo "Detected branch: ${env.BRANCH_NAME}"
                }
            }
        }

        stage('Build') {
            steps {
                sh "make build DOCKERHUB_USER=$DOCKERHUB_USR BUILD_NUMBER=$IMAGE_TAG"
            }
        }

        stage('Push') {
            steps {
                sh '''
                    echo "$DOCKERHUB_PSW" | docker login -u "$DOCKERHUB_USR" --password-stdin
                '''
                sh "make push DOCKERHUB_USER=$DOCKERHUB_USR BUILD_NUMBER=$IMAGE_TAG"
            }
        }

        stage('Deploy') {
            steps {
                script {
                    def namespace = "dev"
                    echo "Deploying branch: ${env.BRANCH_NAME}"
                    switch(env.BRANCH_NAME) {
                        case "develop":
                            namespace = "dev"
                            break
                        case "staging":
                            namespace = "staging"
                            break
                        case "main":
                            namespace = "prod"
                            break
                        default:
                            namespace = "dev"
                    }
                    sh """
                        helm upgrade --install ${APP_NAME} deploy/${APP_NAME} \\
                            --namespace ${namespace} \\
                            --set image.repository=${DOCKERHUB_USR}/${APP_NAME} \\
                            --set image.tag=${IMAGE_TAG}
                    """
                }
            }
        }

    }

    post {
        always {
            sh "docker logout"
        }
    }
}
