pipeline {
    agent any

    environment {
        DOCKERHUB = credentials('d87db04c-92b2-4ade-ab17-ceba28868239')  // Jenkins credential ID: username + password
    }

    stages {

        stage('Build') {
            steps {
                sh "make build"
            }
        }

        stage('Push') {
            steps {
                sh '''
                    echo "$DOCKERHUB_PSW" | docker login -u "$DOCKERHUB_USR" --password-stdin
                '''
                sh "make push"
            }
        }

        stage('Deploy') {
            steps {
                sh "make deploy"
            }
        }
    }

    post {
        always {
            sh "docker logout"
        }
    }
}
